import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";  // Import Header
// import Footer from "@/components/Footer";  // Import Footer
import { Raleway } from "next/font/google";
// import ScrollToTop from "@/components/ScrollToTop";

const raleway = Raleway({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        {/* <ScrollToTop /> */}
        <Header />
        <main className="min-h-screen">{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
